#!/bin/bash

LIBDIR="/usr/local/lib/ddFast"
SCRIPT="$LIBDIR/ddfast.sh"

if [[ ! -f "$SCRIPT" ]]; then
  sudo mkdir -p "$LIBDIR"
  sudo curl -fsSL https://raw.githubusercontent.com/lucysgutz/ddFast/main/ddfast.sh -o "$SCRIPT"
  sudo chmod +x "$SCRIPT"
fi

sudo "$SCRIPT" "$@"
